application: samdp-website
version: alpha-004
module: default
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1 
  min_pending_latency: 500ms  # default value
  max_pending_latency: 500ms
  max_concurrent_requests: 79
  

handlers:
- url: /css
  static_dir: public/css

- url: /admin
  script: main.app
  login: admin

- url: /manage-users
  script: main.app
  login: admin

- url: /chat-room
  script: main.app
  login: required

 
- url: /images
  static_dir: public/images
 
- url: /profile
  script: main.app
  login: required  
  
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
  
- name: ssl
  version: latest  



